# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Behrad Khodayar
#email:
description: > # this means to ignore newlines until "baseurl:"
  Only as an online business card. Don't check back as it's not regularly updated
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://behrad.khodayar.me" # the base hostname & protocol for your site
twitter_username: behradkhodayar
github_username:  behradkhodayar

# Build settings
markdown: kramdown
